services:
  paywatcher:
    container_name: paywatcher_db
    image: postgres:15-alpine3.18
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
